# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Do Thanh Dat
title: Software Engineer
email: datbavip.computer@gmail.com
website: www.datdt.com

# Social links
# twitter_username: facespics
github_username:  datbavip10
# dribbble_username: jekyll
facebook_username: datbavip.computer
# flickr_username: jekyll
instagram_username: datbavip10
linkedin_username: datbavip.computer
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Java Spring Boot</mark> and <mark>PHP</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests software engineering some of my other interests and hobbies are:
   - Data Structure & Algorithm
   - Music Producing
   - Badminton, Soccer

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
